apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
- ./kuttl-test/e2e/
namespace: samba-operator-system
startKIND: false
parallel: 1
timeout: 60
commands:
  - script: (cd ../samba-operator/ && make deploy)