apiVersion: v1
kind: Secret
metadata:
  name: smbuser
type: Opaque
stringData:
  demousers: |
    {
      "samba-container-config": "v0",
      "users": {
        "all_entries": [
          {
            "name": "smbuser1",
            "password": "redhat"
          },
          {
            "name": "smbuser2",
            "password": "redhat"
          }
        ]
      }
    }