---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smbclient-config

---
apiVersion: v1
kind: Pod
metadata:
  name: smbclient
  labels:
    app: samba-operator-test-smbclient
spec:
  containers:
    - name: client
status:
  phase: Running