---
apiVersion: v1
kind: Secret
metadata:
  name: smbuser
type: Opaque
stringData:
  demousers: |
    {
      "samba-container-config": "v0",
      "users": {
        "all_entries": [
          {
            "name": "smbuser1",
            "password": "redhat"
          },
          {
            "name": "smbuser2",
            "password": "redhat"
          }
        ]
      }
    }

---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbSecurityConfig
metadata:
  name: mysmbusers
spec:
  mode: user
  users:
    secret: smbuser
    key: demousers

---
apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: myshare
spec:
  securityConfig: mysmbusers
  readOnly: false
  storage:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi