apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
- script: sleep 5
- script: kubectl exec smbclient -n samba-operator-system -- smbclient -U smbuser1%redhat '//myshare.samba-operator-system.svc.cluster.local/myshare' -c "mkdir demo;ls"